#
# Module manifest for module 'module'
#
# Generated by: pwujczyk
#
# Generated on: 5/26/2018 7:39:17 PM
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ProductivityTools.FindPhotographDuplicates.psm1'

# Version number of this module.
ModuleVersion = '0.0.14'

# ID used to uniquely identify this module
GUID = 'b180fb80-d09b-46fb-b69f-2cb9e7105564'

# Author of this module
Author = 'Pawel Wujczyk'

# Description of the functionality provided by this module
Description = 'It finds all photographs in the master and the slave directory, after this it compares them by date and time taken and optionally by size and name. It can then remove all duplicates or return paths to duplicates. Before removing pictures can be checked in compare directory'

# Functions to export from this module
FunctionsToExport = @('Find-PhotographDuplicates','Find-PhotographDuplicatesInDirectory','Prepare-PhotographDuplicateFile')

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
